name: Calculate codingExperience

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:
jobs:
  update_experience:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update coding experience
        uses: actions/github-script@v5

        with:
          github-token: ${{ secrets.METRICS_TOKEN }}
          script: |
            const fs = require('fs');

            const startDate = new Date('2015-04-05');
            const today = new Date();
            const years = Math.floor((today - startDate) / (1000 * 60 * 60 * 24 * 365));

            let readme = fs.readFileSync('README.md', 'utf8');
            console.log(`Original README file:\n${readme}`);
            readme = readme.replace(/{{codingExperience}}/, `${years}`);
            console.log(`Original README file:\n${readme}`);
            fs.writeFileSync('README.md', readme);
